void movl(char *, char *);
void addl(char *, char *);
void subl(char *, char *);
void imull(char *, char *);
void idivl(char *);
void negl(char *);
void pushl(char *);
void xorl(char *, char *);
void call(char *);
void lcomm(char*, char*);
